"""add tool_runs table

Revision ID: dbc06134de8d
Revises: dabbfa952be2
Create Date: 2026-03-09 16:08:32.051261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbc06134de8d'
down_revision: Union[str, Sequence[str], None] = 'dabbfa952be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'TIMEOUT', name='tool_run_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_runs_case_id'), 'tool_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_tool_runs_status'), 'tool_runs', ['status'], unique=False)
    op.create_index(op.f('ix_tool_runs_tool_name'), 'tool_runs', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_runs_tool_name'), table_name='tool_runs')
    op.drop_index(op.f('ix_tool_runs_status'), table_name='tool_runs')
    op.drop_index(op.f('ix_tool_runs_case_id'), table_name='tool_runs')
    op.drop_table('tool_runs')
    # ### end Alembic commands ###
