# app/core/events.py

class AuditEvent:
    CASE_CREATED = "CASE_CREATED"
    CASE_VIEWED = "CASE_VIEWED"
    CASES_LISTED = "CASES_LISTED"
    CASE_NOT_FOUND = "CASE_NOT_FOUND"
    TOOL_RUN_STARTED = "TOOL_RUN_STARTED"
    TOOL_RUN_COMPLETED = "TOOL_RUN_COMPLETED"
    TOOL_RUN_FAILED = "TOOL_RUN_FAILED"


class ActorType:
    SYSTEM = "system"
    HUMAN = "human"
    AI = "ai"


TOOL_RUN_STARTED = AuditEvent.TOOL_RUN_STARTED
TOOL_RUN_COMPLETED = AuditEvent.TOOL_RUN_COMPLETED
TOOL_RUN_FAILED = AuditEvent.TOOL_RUN_FAILED